# Generated by Django 4.2.16 on 2025-07-27 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("upload", "0003_delete_watchparty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название комнаты"
                    ),
                ),
                (
                    "limit_participants",
                    models.IntegerField(default=10, verbose_name="Участники"),
                ),
                ("is_private", models.BooleanField(verbose_name="Приватная")),
                (
                    "current_time",
                    models.FloatField(
                        default=0.0, verbose_name="Текущее время видео"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_parties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организатор",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="joined_parties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_parties",
                        to="upload.video",
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комната просмотра",
                "verbose_name_plural": "Комнаты просмотра",
                "ordering": ["-created_at"],
            },
        ),
    ]
