# Generated by Django 4.2.16 on 2025-07-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="room_image",
            field=models.ImageField(
                blank=True,
                default=None,
                upload_to="thumbnails/rooms_images/%Y/%m/%d/",
                verbose_name="Изображение комнаты",
            ),
        ),
    ]
