# Generated by Django 4.2.16 on 2025-07-28 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rooms", "0002_watchparty_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchparty",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_parties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
    ]
