# Generated by Django 4.2.16 on 2025-08-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_remove_video_views"),
        (
            "rooms",
            "0005_alter_chatmessage_options_alter_chatmessage_content_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="playlist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_parties",
                to="upload.playlist",
                verbose_name="Плейлист",
            ),
        ),
        migrations.AlterField(
            model_name="watchparty",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="Приватная"),
        ),
        migrations.AlterField(
            model_name="watchparty",
            name="limit_participants",
            field=models.IntegerField(
                default=10, verbose_name="Лимит участников"
            ),
        ),
        migrations.AlterField(
            model_name="watchparty",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_parties",
                to="upload.video",
                verbose_name="Видео",
            ),
        ),
    ]
