# Generated by Django 4.2.16 on 2026-04-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0007_watchparty_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Используется, если видео не загружено на сайт",
                null=True,
                verbose_name="Внешняя ссылка (YouTube, Google Drive)",
            ),
        ),
    ]
