# Generated by Django 4.2.16 on 2026-04-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_watchparty_external_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="external_title",
            field=models.CharField(
                blank=True,
                help_text="Заполняется автоматически при сохранении",
                max_length=300,
                null=True,
                verbose_name="Название внешнего видео",
            ),
        ),
    ]
