version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: coto_postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./for_docker/postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - coto_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  redis:
    image: redis:7-alpine
    container_name: coto_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file: .env
    volumes:
      - ./for_docker/redis_data:/data
    restart: always
    networks:
      - coto_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  coto:
    build: .
    container_name: coto_django
    env_file: .env
    volumes:
      - ./logs/django:/coto/logs
      - ./media:/coto/media
      - ./static_dev:/coto/static
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - coto_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  celery:
    build: .
    container_name: coto_celery
    env_file: .env
    command: celery -A coto worker --loglevel=INFO --logfile=/coto/logs/celery.log
    volumes:
      - ./logs/celery:/coto/logs
      - ./media:/coto/media
    depends_on:
      - redis
      - postgres
      - coto
    restart: always
    networks:
      - coto_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # nginx for development (no SSL)
  nginx-dev:
    image: nginx:latest
    container_name: coto_nginx_dev
    profiles: ["dev"]
    ports:
      - "80:80"
    volumes:
      - ./for_docker/nginx-confs/coto_dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static_dev:/coto/static:ro
      - ./media:/coto/media:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - coto
    restart: always
    networks:
      - coto_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # nginx + certbot for production
  nginx-prod:
    image: jonasal/nginx-certbot:latest
    container_name: coto_nginx_prod
    profiles: ["prod"]
    env_file: .env
    environment:
      - NGINX_MAX_BODY_SIZE=50G
      - STAGING=${CERTBOT_STAGING}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - RENEWAL_INTERVAL=${RENEWAL_INTERVAL}
      - DOMAIN_LIST=${DOMAIN_LIST}
      - USE_ECDSA=1
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=2048
      - ELLIPTIC_CURVE=secp384r1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./for_docker/nginx-confs/coto_prod.conf:/etc/nginx/user_conf.d/coto.conf:ro
      - ./static_dev:/coto/static:ro
      - ./media:/coto/media:rw
      - ./for_docker/nginx-body:/var/lib/nginx/body:rw
      - ./logs/nginx:/var/log/nginx
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - coto
    restart: always
    networks:
      - coto_net
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  coto_net:
    driver: bridge
