# Generated by Django 4.2.16 on 2025-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Размер файла (в байтах)"
            ),
        ),
    ]
