# Generated by Django 4.2.16 on 2025-07-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_video_file_size"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WatchParty",
        ),
    ]
