# Generated by Django 4.2.16 on 2025-08-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_delete_watchparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="hls_manifest",
            field=models.FileField(
                blank=True,
                help_text="Путь до файла master.m3u8",
                null=True,
                upload_to="videos/hls_manifests/",
            ),
        ),
    ]
