# Generated by Django 4.2.16 on 2025-08-10 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("upload", "0004_video_hls_manifest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="playlists/covers/%Y/%m/%d/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_playlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Плейлист",
                "verbose_name_plural": "Плейлисты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Сезон"
                    ),
                ),
                (
                    "episode_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Серия"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Порядок отображения в плейлисте",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="upload.playlist",
                        verbose_name="Плейлист",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_playlists",
                        to="upload.video",
                        verbose_name="Видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эпизод плейлиста",
                "verbose_name_plural": "Эпизоды плейлиста",
                "ordering": ["season_number", "episode_number", "order"],
                "unique_together": {
                    ("playlist", "season_number", "episode_number")
                },
            },
        ),
    ]
