# Generated by Django 4.2.16 on 2025-08-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0005_playlist_playlistitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="views",
        ),
    ]
