# Generated by Django 4.2.16 on 2025-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_remove_video_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="hls_log",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="video",
            name="hls_progress",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="hls_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
