# Generated by Django 4.2.16 on 2025-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0007_video_hls_log_video_hls_progress_video_hls_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="hls_status",
            field=models.CharField(
                blank=True, default="awaiting processing", max_length=32
            ),
        ),
    ]
